"""
Slides service: generate a professional PowerPoint deck (.pptx) from
protocol analysis data.

Uses python-pptx.  Charts are embedded as PNG images generated by chart_service.
Each slide maps to one decision-relevant section of the report.

Slide structure:
  0  Cover
  1  Executive Summary
  2  Precedent Posture (gauge + key numbers)
  3  Design Domain Alignment (radar chart)
  4  Enrollment Benchmark (box-and-whisker)
  5  Trial Duration Comparison
  6  Design Differential Matrix (table)
  7  Top Action Register
  8  Endpoint Evidence (distribution chart)
  9  PubMed Literature Evidence
  10 Comparator Exemplars (table)
  11 Audit & Methodology
"""

from __future__ import annotations

import io
from datetime import datetime, timezone
from typing import Optional

import pandas as pd
from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.util import Inches, Pt, Emu

from trial_design_explorer.domain import ProtocolMetadata
from trial_design_explorer.services.audit_service import current_utc_timestamp
from trial_design_explorer.services.chart_service import (
    generate_alignment_heatmap,
    generate_duration_comparison_chart,
    generate_endpoint_distribution_chart,
    generate_enrollment_benchmark_chart,
    generate_posture_gauge,
    generate_radar_chart,
    generate_sponsor_donut,
)
from trial_design_explorer.services.comparison_service import (
    build_action_register,
    build_design_differential_table,
    build_trial_exemplar_table,
    recommendations_to_dataframe,
)
from trial_design_explorer.services.protocol_service import protocol_metadata_from_session

# ── Colour palette ─────────────────────────────────────────────────────────────
NAVY   = RGBColor(0x15, 0x32, 0x4A)
TEAL   = RGBColor(0x1F, 0x5B, 0x7A)
RED    = RGBColor(0xC0, 0x56, 0x3D)
AMBER  = RGBColor(0xF5, 0xA6, 0x23)
SLATE  = RGBColor(0x5F, 0x6B, 0x7A)
WHITE  = RGBColor(0xFF, 0xFF, 0xFF)
SOFT   = RGBColor(0xED, 0xF3, 0xF7)
BORDER = RGBColor(0xD5, 0xDC, 0xE3)

SLIDE_W = Inches(13.33)
SLIDE_H = Inches(7.5)


# ── Helpers ────────────────────────────────────────────────────────────────────

def _rgb_hex(rgb: RGBColor) -> str:
    return f"{rgb[0]:02X}{rgb[1]:02X}{rgb[2]:02X}"


def _add_slide(prs: Presentation, layout_idx: int = 6):
    """Add a blank slide (layout 6 = blank in most default themes)."""
    layout = prs.slide_layouts[min(layout_idx, len(prs.slide_layouts) - 1)]
    return prs.slides.add_slide(layout)


def _rect(slide, left, top, width, height, fill_rgb: Optional[RGBColor] = None,
          line_rgb: Optional[RGBColor] = None, line_width_pt: float = 0.0):
    shape = slide.shapes.add_shape(
        1,  # MSO_SHAPE_TYPE.RECTANGLE
        left, top, width, height,
    )
    shape.line.fill.background()
    if fill_rgb:
        shape.fill.solid()
        shape.fill.fore_color.rgb = fill_rgb
    else:
        shape.fill.background()
    if line_rgb:
        shape.line.color.rgb = line_rgb
        shape.line.width = Pt(line_width_pt)
    else:
        shape.line.fill.background()
    return shape


def _text_box(slide, left, top, width, height, text: str,
              font_size: int = 11, bold: bool = False,
              color: RGBColor = NAVY, align=PP_ALIGN.LEFT,
              wrap: bool = True) -> None:
    txb = slide.shapes.add_textbox(left, top, width, height)
    txb.word_wrap = wrap
    tf = txb.text_frame
    tf.word_wrap = wrap
    para = tf.paragraphs[0]
    para.alignment = align
    run = para.add_run()
    run.text = text
    run.font.size = Pt(font_size)
    run.font.bold = bold
    run.font.color.rgb = color
    run.font.name = "Calibri"


def _heading_bar(slide, title: str, subtitle: str = "") -> None:
    """Navy header bar at the top of a content slide."""
    _rect(slide, Inches(0), Inches(0), SLIDE_W, Inches(0.9), fill_rgb=NAVY)
    _text_box(slide, Inches(0.2), Inches(0.08), Inches(12.5), Inches(0.45),
              title, font_size=20, bold=True, color=WHITE)
    if subtitle:
        _text_box(slide, Inches(0.2), Inches(0.52), Inches(12.5), Inches(0.35),
                  subtitle, font_size=10, color=RGBColor(0xB0, 0xC4, 0xD8))


def _add_image_from_buf(slide, buf: io.BytesIO,
                         left, top, width, height) -> None:
    buf.seek(0)
    slide.shapes.add_picture(buf, left, top, width, height)


def _table_on_slide(slide, df: pd.DataFrame,
                    left, top, width, height,
                    font_size: int = 8) -> None:
    if df.empty:
        return
    rows, cols = len(df) + 1, len(df.columns)
    tbl = slide.shapes.add_table(rows, cols, left, top, width, height).table

    col_w = width // cols
    for ci in range(cols):
        tbl.columns[ci].width = col_w

    # Header
    for ci, col_name in enumerate(df.columns):
        cell = tbl.cell(0, ci)
        cell.text = str(col_name)
        cell.fill.solid()
        cell.fill.fore_color.rgb = NAVY
        p = cell.text_frame.paragraphs[0]
        p.alignment = PP_ALIGN.CENTER
        run = p.runs[0] if p.runs else p.add_run()
        run.font.bold = True
        run.font.color.rgb = WHITE
        run.font.size = Pt(font_size)
        run.font.name = "Calibri"

    # Data rows
    safe_df = df.fillna("").astype(str)
    for ri, row_data in enumerate(safe_df.itertuples(index=False), start=1):
        fill_rgb = SOFT if ri % 2 == 0 else WHITE
        for ci, val in enumerate(row_data):
            cell = tbl.cell(ri, ci)
            cell.text = str(val)[:80]
            cell.fill.solid()
            cell.fill.fore_color.rgb = fill_rgb
            p = cell.text_frame.paragraphs[0]
            p.alignment = PP_ALIGN.LEFT
            run = p.runs[0] if p.runs else p.add_run()
            run.font.size = Pt(font_size)
            run.font.color.rgb = NAVY
            run.font.name = "Calibri"


def _footer(slide, page_num: int, total_pages: int) -> None:
    _text_box(
        slide,
        Inches(0.2), Inches(7.2), Inches(9), Inches(0.25),
        "Trial Design Explorer | Clinical Trial Planning Intelligence | Confidential draft",
        font_size=7, color=SLATE,
    )
    _text_box(
        slide,
        Inches(12.3), Inches(7.2), Inches(1.0), Inches(0.25),
        f"{page_num} / {total_pages}",
        font_size=7, color=SLATE, align=PP_ALIGN.RIGHT,
    )


# ── Slide builders ─────────────────────────────────────────────────────────────

def _slide_cover(prs: Presentation, protocol: ProtocolMetadata,
                 page_num: int, total_pages: int) -> None:
    slide = _add_slide(prs)
    # Full-bleed navy background
    _rect(slide, 0, 0, SLIDE_W, SLIDE_H, fill_rgb=NAVY)
    # Left accent bar
    _rect(slide, 0, 0, Inches(0.15), SLIDE_H, fill_rgb=TEAL)

    _text_box(slide, Inches(0.4), Inches(1.4), Inches(11), Inches(0.6),
              "Protocol Intelligence Report",
              font_size=34, bold=True, color=WHITE)
    _text_box(slide, Inches(0.4), Inches(2.15), Inches(11), Inches(0.5),
              "Clinical Trial Design Benchmarking & Decision-Grade Evidence",
              font_size=15, color=RGBColor(0xB0, 0xC4, 0xD8))

    _rect(slide, Inches(0.4), Inches(2.85), Inches(10.5), Pt(1.5), fill_rgb=TEAL)

    meta_lines = [
        f"Protocol:  {protocol.title or 'Not provided'}",
        f"Condition: {protocol.condition or 'Not provided'}",
        f"Sponsor:   {protocol.sponsor or 'Not provided'}",
        f"Phase:     {protocol.phase or 'Not provided'}  |  Study type: {protocol.study_type or 'Not provided'}",
        f"Generated: {current_utc_timestamp()} UTC",
    ]
    for i, line in enumerate(meta_lines):
        _text_box(slide, Inches(0.4), Inches(3.1) + Inches(i * 0.42),
                  Inches(11), Inches(0.38),
                  line, font_size=11,
                  color=RGBColor(0xD0, 0xE4, 0xF0))

    _text_box(slide, Inches(0.4), Inches(6.9), Inches(12), Inches(0.3),
              "Confidential — prepared for clinical development, trial design, and operational planning review.",
              font_size=8, color=SLATE)
    _footer(slide, page_num, total_pages)


def _slide_executive_summary(prs, protocol, metrics, recommendations,
                               page_num, total_pages) -> None:
    slide = _add_slide(prs)
    _heading_bar(slide, "Executive Summary",
                 "Top-line read on precedent posture, evidence strength, and lead actions")
    _footer(slide, page_num, total_pages)

    c_fit = metrics.get("completed_design_fit_pct", "n/a")
    d_fit = metrics.get("disrupted_design_fit_pct", "n/a")
    posture = metrics.get("precedent_posture", "Incomplete")
    cohort = metrics.get("cohort_size", 0)
    evidence = metrics.get("evidence_strength", "Limited")

    kpis = [
        ("Cohort size", str(cohort), TEAL),
        ("Completed fit", f"{c_fit}%" if isinstance(c_fit, (int, float)) else str(c_fit), TEAL),
        ("Disrupted fit", f"{d_fit}%" if isinstance(d_fit, (int, float)) else str(d_fit), RED),
        ("Evidence", evidence, NAVY),
    ]
    for i, (label, value, color) in enumerate(kpis):
        x = Inches(0.3 + i * 3.25)
        _rect(slide, x, Inches(1.0), Inches(3.0), Inches(1.1), fill_rgb=color)
        _text_box(slide, x + Inches(0.1), Inches(1.05), Inches(2.8), Inches(0.4),
                  label, font_size=9, color=WHITE)
        _text_box(slide, x + Inches(0.1), Inches(1.45), Inches(2.8), Inches(0.55),
                  value, font_size=18, bold=True, color=WHITE)

    _text_box(slide, Inches(0.3), Inches(2.25), Inches(12.5), Inches(0.35),
              f"Overall posture: {posture}", font_size=13, bold=True, color=NAVY)

    bullet_items = []
    if protocol.title:
        bullet_items.append(f"Protocol: {protocol.title}")
    if protocol.condition:
        bullet_items.append(f"Clinical focus: {protocol.condition}")
    bullet_items.append(f"Design fit vs completed precedent: {c_fit}%  |  vs disrupted: {d_fit}%")
    if metrics.get("missing_core_fields"):
        bullet_items.append(f"Specification gaps: {', '.join(metrics['missing_core_fields'])}")
    for rec in (recommendations or [])[:3]:
        priority = rec.get("Priority", "")
        action = rec.get("Recommendation", "")
        bullet_items.append(f"[{priority}] {action}")

    y = Inches(2.7)
    for item in bullet_items[:7]:
        _rect(slide, Inches(0.3), y, Inches(0.06), Inches(0.22), fill_rgb=TEAL)
        _text_box(slide, Inches(0.5), y - Inches(0.02), Inches(12.2), Inches(0.32),
                  item, font_size=10, color=NAVY)
        y += Inches(0.38)


def _slide_posture_gauge(prs, metrics, page_num, total_pages) -> None:
    slide = _add_slide(prs)
    _heading_bar(slide, "Precedent Posture",
                 "How the draft design compares to completed vs disrupted trial precedent")
    _footer(slide, page_num, total_pages)

    gauge_buf = generate_posture_gauge(metrics, width_in=5.5, height_in=3.5)
    _add_image_from_buf(slide, gauge_buf, Inches(0.3), Inches(1.0),
                        Inches(5.5), Inches(3.5))

    right_x = Inches(6.2)
    stats = [
        ("Completed fit", metrics.get("completed_design_fit_pct"), TEAL),
        ("Disrupted fit", metrics.get("disrupted_design_fit_pct"), RED),
        ("Net gap", metrics.get("precedent_gap_pct"), NAVY),
        ("Evidence strength", metrics.get("evidence_strength", "Limited"), NAVY),
        ("Completed studies", metrics.get("completed_cohort_size", 0), TEAL),
        ("Disrupted studies", metrics.get("disrupted_cohort_size", 0), RED),
    ]
    for i, (label, value, color) in enumerate(stats):
        y = Inches(1.1) + Inches(i * 0.75)
        _rect(slide, right_x, y, Inches(1.0), Inches(0.55), fill_rgb=color)
        val_str = f"{value}%" if isinstance(value, float) else str(value)
        _text_box(slide, right_x + Inches(0.05), y + Inches(0.08), Inches(0.9), Inches(0.35),
                  val_str, font_size=14, bold=True, color=WHITE, align=PP_ALIGN.CENTER)
        _text_box(slide, right_x + Inches(1.1), y + Inches(0.1), Inches(5.5), Inches(0.35),
                  label, font_size=11, color=NAVY)


def _slide_radar(prs, metrics, page_num, total_pages) -> None:
    slide = _add_slide(prs)
    _heading_bar(slide, "Design Domain Alignment",
                 "Alignment across 7 design domains — completed vs disrupted precedent")
    _footer(slide, page_num, total_pages)

    buf = generate_radar_chart(metrics, width_in=7, height_in=5.5)
    _add_image_from_buf(slide, buf, Inches(0.2), Inches(0.95), Inches(7.0), Inches(5.5))

    rows = metrics.get("alignment_by_domain", [])
    right_x = Inches(7.6)
    _text_box(slide, right_x, Inches(1.0), Inches(5.5), Inches(0.3),
              "Domain signals at a glance", font_size=10, bold=True, color=NAVY)
    for i, row in enumerate(rows[:7]):
        y = Inches(1.4) + Inches(i * 0.68)
        sig = row.get("Signal", "")
        color = TEAL if "Completed" in sig else (RED if "Disrupted" in sig else SLATE)
        _rect(slide, right_x, y, Inches(5.5), Inches(0.55), fill_rgb=SOFT,
              line_rgb=BORDER, line_width_pt=0.5)
        domain_text = f"{row['Domain']}: {row.get('Protocol Choice', '')} — {sig}"
        _text_box(slide, right_x + Inches(0.08), y + Inches(0.08), Inches(5.3), Inches(0.38),
                  domain_text, font_size=8.5, color=color)


def _slide_enrollment(prs, metrics, page_num, total_pages) -> None:
    slide = _add_slide(prs)
    _heading_bar(slide, "Enrollment Benchmark",
                 "Protocol target vs completed and disrupted precedent IQR ranges")
    _footer(slide, page_num, total_pages)

    buf = generate_enrollment_benchmark_chart(metrics, width_in=7.5, height_in=4.5)
    _add_image_from_buf(slide, buf, Inches(0.2), Inches(0.95), Inches(7.5), Inches(4.5))

    right_x = Inches(8.1)
    items = [
        ("Protocol target", metrics.get("enrollment_target"), AMBER),
        ("Completed median", metrics.get("completed_enrollment_median"), TEAL),
        ("Completed P25–P75",
         f"{metrics.get('completed_enrollment_p25', '—')} – {metrics.get('completed_enrollment_p75', '—')}",
         TEAL),
        ("Disrupted median", metrics.get("disrupted_enrollment_median"), RED),
        ("Disrupted P25–P75",
         f"{metrics.get('disrupted_enrollment_p25', '—')} – {metrics.get('disrupted_enrollment_p75', '—')}",
         RED),
    ]
    _text_box(slide, right_x, Inches(1.0), Inches(4.8), Inches(0.3),
              "Key numbers", font_size=10, bold=True, color=NAVY)
    for i, (label, value, color) in enumerate(items):
        y = Inches(1.4) + Inches(i * 0.82)
        val_str = f"{value:,}" if isinstance(value, (int, float)) else str(value or "n/a")
        _rect(slide, right_x, y, Inches(4.8), Inches(0.65), fill_rgb=SOFT,
              line_rgb=BORDER, line_width_pt=0.5)
        _text_box(slide, right_x + Inches(0.08), y + Inches(0.03), Inches(4.6), Inches(0.25),
                  label, font_size=8, color=SLATE)
        _text_box(slide, right_x + Inches(0.08), y + Inches(0.3), Inches(4.6), Inches(0.3),
                  val_str, font_size=13, bold=True, color=color)


def _slide_duration(prs, metrics, page_num, total_pages) -> None:
    slide = _add_slide(prs)
    _heading_bar(slide, "Trial Duration Analysis",
                 "Planned duration vs completed and disrupted precedent cohort ranges")
    _footer(slide, page_num, total_pages)

    buf = generate_duration_comparison_chart(metrics, width_in=8.5, height_in=4.2)
    _add_image_from_buf(slide, buf, Inches(0.2), Inches(1.0), Inches(8.5), Inches(4.2))

    right_x = Inches(9.0)
    items = [
        ("Protocol plan (mo)", metrics.get("protocol_duration_months"), AMBER),
        ("Completed median (mo)", metrics.get("completed_duration_median_months"), TEAL),
        ("Disrupted median (mo)", metrics.get("disrupted_duration_median_months"), RED),
    ]
    _text_box(slide, right_x, Inches(1.0), Inches(4.0), Inches(0.3),
              "Duration stats", font_size=10, bold=True, color=NAVY)
    for i, (label, value, color) in enumerate(items):
        y = Inches(1.4) + Inches(i * 0.9)
        val_str = f"{value:.0f}" if isinstance(value, float) else str(value or "n/a")
        _rect(slide, right_x, y, Inches(4.0), Inches(0.7), fill_rgb=SOFT,
              line_rgb=BORDER, line_width_pt=0.5)
        _text_box(slide, right_x + Inches(0.08), y + Inches(0.04), Inches(3.8), Inches(0.25),
                  label, font_size=8, color=SLATE)
        _text_box(slide, right_x + Inches(0.08), y + Inches(0.33), Inches(3.8), Inches(0.3),
                  val_str, font_size=16, bold=True, color=color)


def _slide_design_matrix(prs, metrics, page_num, total_pages) -> None:
    slide = _add_slide(prs)
    _heading_bar(slide, "Design Differential Matrix",
                 "Domain-level protocol choice vs completed and disrupted precedent match rates")
    _footer(slide, page_num, total_pages)

    heatmap_buf = generate_alignment_heatmap(metrics, width_in=12, height_in=4.5)
    _add_image_from_buf(slide, heatmap_buf, Inches(0.3), Inches(1.0), Inches(12.5), Inches(5.5))


def _slide_action_register(prs, recommendations, page_num, total_pages) -> None:
    slide = _add_slide(prs)
    _heading_bar(slide, "Action Register",
                 "Priority-ordered design decisions, clarifications, and risk mitigations")
    _footer(slide, page_num, total_pages)

    df = build_action_register(recommendations or [])
    if not df.empty:
        display_cols = [c for c in ["Priority", "Category", "Action Type", "Recommendation", "Evidence"]
                        if c in df.columns]
        df_display = df[display_cols].head(10)
        _table_on_slide(slide, df_display,
                        Inches(0.25), Inches(0.95),
                        Inches(12.8), Inches(6.2),
                        font_size=8)
    else:
        _text_box(slide, Inches(0.3), Inches(2.0), Inches(12), Inches(0.5),
                  "No actions were generated for this analysis run.",
                  font_size=11, color=SLATE)


def _slide_endpoint_evidence(prs, metrics, page_num, total_pages) -> None:
    slide = _add_slide(prs)
    _heading_bar(slide, "Endpoint Evidence",
                 "Endpoint category prevalence in completed vs disrupted precedent cohorts")
    _footer(slide, page_num, total_pages)

    buf = generate_endpoint_distribution_chart(metrics, width_in=7.5, height_in=5.0)
    _add_image_from_buf(slide, buf, Inches(0.2), Inches(1.0), Inches(7.5), Inches(5.0))

    donut_buf = generate_sponsor_donut(metrics, width_in=4.5, height_in=4.0)
    _add_image_from_buf(slide, donut_buf, Inches(8.2), Inches(1.0), Inches(4.8), Inches(4.0))


def _slide_pubmed_evidence(prs, pubmed_articles, page_num, total_pages) -> None:
    slide = _add_slide(prs)
    _heading_bar(slide, "Literature Evidence (PubMed)",
                 "Peer-reviewed studies supporting the design rationale — sourced via NCBI PubMed")
    _footer(slide, page_num, total_pages)

    if not pubmed_articles:
        _text_box(slide, Inches(0.3), Inches(2.0), Inches(12), Inches(0.5),
                  "No PubMed articles were retrieved for this analysis.",
                  font_size=11, color=SLATE)
        return

    rows = []
    for art in pubmed_articles[:8]:
        a = art if isinstance(art, dict) else art.to_dict()
        rows.append({
            "PMID": a.get("pmid", ""),
            "Authors (first)": (a.get("authors", "").split(",")[0] + " et al.")[:30],
            "Year": a.get("year", ""),
            "Journal": a.get("journal", "")[:30],
            "Title": a.get("title", "")[:70],
        })
    df = pd.DataFrame(rows)
    _table_on_slide(slide, df,
                    Inches(0.25), Inches(0.95),
                    Inches(12.8), Inches(5.8),
                    font_size=8)

    _text_box(slide, Inches(0.3), Inches(6.9), Inches(12), Inches(0.3),
              "Source: PubMed / NCBI E-utilities (free access). All citations are auditable and traceable.",
              font_size=7.5, color=SLATE)


def _slide_exemplars(prs, top_trials_df, page_num, total_pages) -> None:
    slide = _add_slide(prs)
    _heading_bar(slide, "Comparator Exemplars",
                 "Representative completed and disrupted precedent studies from the matched cohort")
    _footer(slide, page_num, total_pages)

    if top_trials_df is not None and not top_trials_df.empty:
        df = build_trial_exemplar_table(top_trials_df, limit=12)
        cols = [c for c in ["Comparator Lens", "Status", "NCT ID", "Title", "Enrollment", "Sponsor"]
                if c in df.columns]
        _table_on_slide(slide, df[cols],
                        Inches(0.25), Inches(0.95),
                        Inches(12.8), Inches(6.1),
                        font_size=8)
    else:
        _text_box(slide, Inches(0.3), Inches(2.0), Inches(12), Inches(0.5),
                  "No comparator exemplar data available.", font_size=11, color=SLATE)


def _slide_audit(prs, protocol, audit_log, page_num, total_pages) -> None:
    slide = _add_slide(prs)
    _heading_bar(slide, "Audit Trail & Methodology",
                 "Traceable record of all actions, extractions, comparisons, and exports")
    _footer(slide, page_num, total_pages)

    methodology = (
        "Source trials retrieved from ClinicalTrials.gov registry (API v2).  Trials were classified "
        "as completed (COMPLETED) or disrupted (TERMINATED / SUSPENDED / WITHDRAWN) and used as two "
        "distinct comparator lenses.  Protocol fields were extracted from uploaded documents using "
        "deterministic heuristics and optionally LLM-assisted structured parsing.  All outputs are "
        "decision-support intelligence — they do not replace clinical, statistical, operational, or "
        "regulatory judgment."
    )
    _text_box(slide, Inches(0.3), Inches(1.0), Inches(12.5), Inches(1.1),
              methodology, font_size=9.5, color=NAVY)

    if audit_log:
        events = audit_log[-12:]
        rows = []
        for ev in events:
            rows.append({
                "Timestamp": str(ev.get("timestamp", ""))[:19],
                "Action": str(ev.get("action", "")).replace("_", " ").title(),
                "Actor": str(ev.get("actor", "system")).title(),
                "Details": str(ev.get("details", ""))[:80],
            })
        df = pd.DataFrame(rows)
        _table_on_slide(slide, df,
                        Inches(0.25), Inches(2.2),
                        Inches(12.8), Inches(4.8),
                        font_size=7.5)


# ── Main entry point ──────────────────────────────────────────────────────────

def generate_slides_pptx(
    file_path: str,
    protocol_meta,
    comparison_metrics: dict,
    recommendations: list[dict],
    audit_log: list[dict],
    top_trials_df=None,
    pubmed_articles: Optional[list] = None,
) -> str:
    """
    Generate a professional PowerPoint deck and write it to file_path.

    Returns the file_path on success.
    """
    protocol = (
        protocol_meta
        if isinstance(protocol_meta, ProtocolMetadata)
        else protocol_metadata_from_session(protocol_meta)
    )
    metrics = comparison_metrics or {}

    prs = Presentation()
    prs.slide_width = SLIDE_W
    prs.slide_height = SLIDE_H

    # Ensure we have enough layouts — fill with blank if needed
    while len(prs.slide_layouts) < 7:
        pass  # default pptx has at least 11 layouts

    total_pages = 11

    _slide_cover(prs, protocol, 1, total_pages)
    _slide_executive_summary(prs, protocol, metrics, recommendations, 2, total_pages)
    _slide_posture_gauge(prs, metrics, 3, total_pages)
    _slide_radar(prs, metrics, 4, total_pages)
    _slide_enrollment(prs, metrics, 5, total_pages)
    _slide_duration(prs, metrics, 6, total_pages)
    _slide_design_matrix(prs, metrics, 7, total_pages)
    _slide_action_register(prs, recommendations, 8, total_pages)
    _slide_endpoint_evidence(prs, metrics, 9, total_pages)
    _slide_pubmed_evidence(prs, pubmed_articles or [], 10, total_pages)
    _slide_exemplars(prs, top_trials_df, 11, total_pages)

    prs.save(file_path)
    return file_path
